[workspace]
members = [
    "pk",
    "share_encryption",
    "share_decryption",
    "sk_share_computation_base",
    "e_sm_share_computation_base",
    "share_computation_chunk",
    "share_computation_wrapper"
]

