services:
  cn1:
    image: ghcr.io/gnosisguild/ciphernode:${VERSION:-latest}
    volumes:
      - ./configs/cn1.yaml:/home/ciphernode/.config/enclave/config.yaml:ro,Z
      - cn1-data:/home/ciphernode/.local/share/enclave
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - 9091:9091
    # command: nc -l -p 9091

  cn2:
    image: ghcr.io/gnosisguild/ciphernode:${VERSION:-latest}
    volumes:
      - ./configs/cn2.yaml:/home/ciphernode/.config/enclave/config.yaml:ro,Z
      - cn2-data:/home/ciphernode/.local/share/enclave
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - secrets.json
    depends_on:
      - cn1
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - 9092:9092
    # command: nc -l -p 9092

  cn3:
    image: ghcr.io/gnosisguild/ciphernode:${VERSION:-latest}
    volumes:
      - ./configs/cn3.yaml:/home/ciphernode/.config/enclave/config.yaml:ro,Z
      - cn3-data:/home/ciphernode/.local/share/enclave
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - secrets.json
    depends_on:
      - cn1    
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "false"
    ports:
      - 9093:9093
    # command: nc -l -p 9093


  aggregator:
    image: ghcr.io/gnosisguild/ciphernode:${VERSION:-latest}
    volumes:
      - ./configs/agg.yaml:/home/ciphernode/.config/enclave/config.yaml:ro,Z
      - agg-data:/home/ciphernode/.local/share/enclave
    depends_on:
      - cn1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    secrets:
      - secrets.json
    environment:
      RUST_LOG: "info"
      AGGREGATOR: "true"
    ports:
      - 9094:9094
    # command: nc -l -p 9094


secrets:
  secrets.json:
    file: ./configs/secrets.json
    
volumes:
  cn1-data:
  cn2-data:
  cn3-data:
  agg-data:

