// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.
pragma solidity >=0.8.27;

import { IDecryptionVerifier } from "../../interfaces/IDecryptionVerifier.sol";
import { ICircuitVerifier } from "../../interfaces/ICircuitVerifier.sol";

/**
 * @title BfvDecryptionVerifier
 * @notice Verifies the DecryptionAggregator (EVM) proof produced by the
 *         recursive aggregation pipeline (C6 folds + C7/decrypted_shares
 *         verified internally) and binds it to the full on-chain call context.
 * @dev Used when the Enclave is configured with encryptionSchemeId
 *      keccak256("fhe.rs:BFV").
 *
 *      Expected `publicInputs` layout:
 *        [0]                                       = C6_FOLD_KEY_HASH (anchor)
 *        [1]                                       = C7_KEY_HASH      (anchor)
 *        [2 .. length - 101)                       = circuit-internal slots
 *                                                    (party ids, sk, esm, ...)
 *        [length - 101]                            = domain binding hash
 *        [length - 100 .. length)                  = plaintext message coefficients
 *                                                    (100 × u64 LE; see MESSAGE_COEFFS_COUNT)
 *
 *      The two VK-hash slots are checked against contract immutables set at
 *      construction; this anchors the recursive aggregation trust and
 *      prevents a malicious aggregator from substituting a forged sub-VK whose
 *      hash also lands in slots [0]/[1].
 *
 *      The domain binding is `keccak256(abi.encode(chainid, this, e3Id,
 *      committeeRoot, sortedNodes, ciphertextOutputHash, committeePublicKey,
 *      plaintextOutputHash))`, recomputed on chain on every call and required
 *      to equal `publicInputs[length - 101]`. This defeats cross-chain /
 *      cross-deployment / cross-e3 / cross-ciphertext replay.
 *
 *      NOTE — relaxation: see the analogous note on `BfvPkVerifier`. The
 *      honk verifier is autogenerated and does not yet constrain the
 *      domain-binding slot internally; the wrapper enforces it at the call
 *      boundary. Full circuit-level enforcement requires regenerating the
 *      Noir circuits with a dedicated `domain_binding: pub Field` input and
 *      is tracked as future work.
 */
contract BfvDecryptionVerifier is IDecryptionVerifier {
    /// @dev Message is always the last 100 public inputs (100 uint64 coeffs = 800 bytes plaintext).
    uint256 constant MESSAGE_COEFFS_COUNT = 100;

    /// @notice Underlying Honk verifier for the DecryptionAggregator circuit.
    ICircuitVerifier public immutable circuitVerifier;

    /// @notice keccak256 commitment to the C6-fold recursive VK; expected at
    ///         `publicInputs[0]`. Provenance: `bb verify_key -b
    ///         circuits/bin/recursive_aggregation/c6_fold/target/...` — pinned
    ///         at deployment time.
    bytes32 public immutable C6_FOLD_KEY_HASH;

    /// @notice keccak256 commitment to the C7 (decrypted_shares_aggregation)
    ///         recursive VK; expected at `publicInputs[1]`. Same provenance.
    bytes32 public immutable C7_KEY_HASH;

    constructor(
        address _circuitVerifier,
        bytes32 _c6FoldKeyHash,
        bytes32 _c7KeyHash
    ) {
        circuitVerifier = ICircuitVerifier(_circuitVerifier);
        C6_FOLD_KEY_HASH = _c6FoldKeyHash;
        C7_KEY_HASH = _c7KeyHash;
    }

    /// @inheritdoc IDecryptionVerifier
    function verify(
        uint256 e3Id,
        uint256 committeeRoot,
        address[] calldata sortedNodes,
        bytes32 ciphertextOutputHash,
        bytes32 committeePublicKey,
        bytes32 plaintextOutputHash,
        bytes calldata proof
    ) external view override returns (bool) {
        (bytes memory rawProof, bytes32[] memory publicInputs) = abi.decode(
            proof,
            (bytes, bytes32[])
        );

        // must hold both VK anchors + domain-binding slot + 100 message coeffs.
        // Minimum is `2 + 1 + MESSAGE_COEFFS_COUNT = 103`.
        if (publicInputs.length < MESSAGE_COEFFS_COUNT + 3) {
            revert InvalidPublicInputsLength();
        }

        // anchor recursive-aggregation trust to immutable VK hashes.
        if (publicInputs[0] != C6_FOLD_KEY_HASH) {
            revert VkHashMismatch();
        }
        if (publicInputs[1] != C7_KEY_HASH) {
            revert VkHashMismatch();
        }

        // Plaintext hash check (existing logic; now reverts on mismatch).
        if (!_verifyPlaintextHash(publicInputs, plaintextOutputHash)) {
            revert PlaintextHashMismatch();
        }

        // bind the proof to (chain, deployment, e3, committee, ciphertext, pk, plaintext).
        bytes32 domainBinding = keccak256(
            abi.encode(
                block.chainid,
                address(this),
                e3Id,
                committeeRoot,
                sortedNodes,
                ciphertextOutputHash,
                committeePublicKey,
                plaintextOutputHash
            )
        );
        if (
            publicInputs[publicInputs.length - MESSAGE_COEFFS_COUNT - 1] !=
            domainBinding
        ) {
            revert DomainBindingMismatch();
        }

        // bubble up as a revert instead of a silent `false`.
        if (!circuitVerifier.verify(rawProof, publicInputs)) {
            revert InvalidProof();
        }
        return true;
    }

    function _verifyPlaintextHash(
        bytes32[] memory publicInputs,
        bytes32 plaintextOutputHash
    ) internal pure returns (bool) {
        uint256 offset = publicInputs.length - MESSAGE_COEFFS_COUNT;
        bytes memory plaintext = new bytes(MESSAGE_COEFFS_COUNT * 8);
        for (uint256 i = 0; i < MESSAGE_COEFFS_COUNT; i++) {
            uint64 coeff = uint64(uint256(publicInputs[offset + i]));
            for (uint256 j = 0; j < 8; j++) {
                plaintext[i * 8 + j] = bytes1(uint8(coeff >> (j * 8)));
            }
        }
        return keccak256(plaintext) == plaintextOutputHash;
    }
}
