// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.
pragma solidity 0.8.28;

import { IPkVerifier } from "../../interfaces/IPkVerifier.sol";
import { ICircuitVerifier } from "../../interfaces/ICircuitVerifier.sol";

/**
 * @title BfvPkVerifier
 * @notice Verifies the DkgAggregator (EVM) proof produced by the recursive
 *         aggregation pipeline (node folds + C5/pk_aggregation verified
 *         internally) and binds it to the full on-chain call context.
 * @dev Used when the Enclave is configured with encryptionSchemeId
 *      keccak256("fhe.rs:BFV").
 *
 *      Expected `publicInputs` layout (last-three-slots layout):
 *        [0]                          = NODES_FOLD_KEY_HASH  (anchor)
 *        [1]                          = C5_KEY_HASH          (anchor)
 *        [2 .. length - 3)            = circuit-internal slots
 *                                       (party ids, expected pk, ...)
 *        [length - 2]                 = domain binding hash
 *        [length - 1]                 = aggregated PK commitment
 *
 *      The two VK-hash slots are checked against contract immutables set at
 *      construction; this anchors the recursive aggregation trust and
 *      prevents a malicious aggregator from substituting a forged sub-VK whose
 *      hash also lands in slots [0]/[1].
 *
 *      The domain binding is `keccak256(abi.encode(chainid, this, e3Id,
 *      committeeRoot, sortedNodes, pkCommitment))`, recomputed on chain on
 *      every call and required to equal `publicInputs[length - 2]`. This
 *      defeats cross-chain / cross-deployment / cross-e3 replay.
 *
 *      NOTE — relaxation: the underlying honk verifier is autogenerated and
 *      does not (yet) constrain the domain-binding slot internally. The
 *      wrapper-side equality check above forces every honest prover to place
 *      the correct value in that slot, but an adversary who can produce a
 *      genuine honk proof with arbitrary values in that slot would also pass.
 *      Full cryptographic enforcement requires regenerating the Noir circuits
 *      with a dedicated `domain_binding: pub Field` input — explicitly
 *      out-of-scope here per the audit-fix hard constraint that
 *      `contracts/verifiers/bfv/honk/*` is untouched. Tracked as future work.
 */
contract BfvPkVerifier is IPkVerifier {
    /// @notice Underlying Honk verifier for the DkgAggregator circuit.
    ICircuitVerifier public immutable circuitVerifier;

    /// @notice keccak256 commitment to the node-fold recursive VK; expected at
    ///         `publicInputs[0]`. Provenance: `bb verify_key -b
    ///         circuits/bin/recursive_aggregation/node_fold/target/...` —
    ///         pinned at deployment time, must match the circuit version the
    ///         aggregator was built against.
    bytes32 public immutable NODES_FOLD_KEY_HASH;

    /// @notice keccak256 commitment to the C5 (pk_aggregation) recursive VK;
    ///         expected at `publicInputs[1]`. Same provenance as above.
    bytes32 public immutable C5_KEY_HASH;

    constructor(
        address _circuitVerifier,
        bytes32 _nodesFoldKeyHash,
        bytes32 _c5KeyHash
    ) {
        circuitVerifier = ICircuitVerifier(_circuitVerifier);
        NODES_FOLD_KEY_HASH = _nodesFoldKeyHash;
        C5_KEY_HASH = _c5KeyHash;
    }

    /// @inheritdoc IPkVerifier
    function verify(
        uint256 e3Id,
        uint256 committeeRoot,
        address[] calldata sortedNodes,
        bytes32 pkCommitment,
        bytes calldata proof
    ) external view override returns (bool) {
        (bytes memory rawProof, bytes32[] memory publicInputs) = abi.decode(
            proof,
            (bytes, bytes32[])
        );

        // minimum length to hold both VK anchors, the domain-binding
        // slot and the pk-commitment slot.
        if (publicInputs.length < 4) {
            revert InvalidPublicInputsLength();
        }

        // anchor recursive-aggregation trust to immutable VK hashes.
        if (publicInputs[0] != NODES_FOLD_KEY_HASH) {
            revert VkHashMismatch();
        }
        if (publicInputs[1] != C5_KEY_HASH) {
            revert VkHashMismatch();
        }

        // Aggregated PK commitment is the last slot.
        if (publicInputs[publicInputs.length - 1] != pkCommitment) {
            revert PkCommitmentMismatch();
        }

        // bind the proof to (chain, deployment, e3, committee, pk).
        bytes32 domainBinding = keccak256(
            abi.encode(
                block.chainid,
                address(this),
                e3Id,
                committeeRoot,
                sortedNodes,
                pkCommitment
            )
        );
        if (publicInputs[publicInputs.length - 2] != domainBinding) {
            revert DomainBindingMismatch();
        }

        // bubble up as a revert instead of a silent `false`.
        if (!circuitVerifier.verify(rawProof, publicInputs)) {
            revert InvalidProof();
        }
        return true;
    }
}
