#!/usr/bin/env bash

while [[ $# -gt 0 ]]; do
  [[ $1 == --api-key ]] && API_KEY="$2" && shift 2 && continue
  [[ $1 == --api-url ]] && API_URL="$2" && shift 2 && continue
  shift
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -n "$API_KEY" && -n "$API_URL" ]]; then
  # BONSAI MODE
  "$SCRIPT_DIR/container" ./scripts/container/start.sh --api-key "$API_KEY" --api-url "$API_URL"
elif [[ -z "$API_KEY" && -z "$API_URL" ]]; then
  # DEV MODE
  "$SCRIPT_DIR/container" ./scripts/container/start.sh
else
  exit 1
fi
