sequenceDiagram
  actor EVM
  actor Node1
  actor DHT 
  actor Node2 
  actor Agg as Aggregator

  EVM -->> Node1: E3Requested
  EVM -->> Node2: E3Requested
  Node1 ->> Node1: determine_index_from_seed(...)
  Node2 ->> Node2: determine_index_from_seed(...)
  Node1 ->> Node1: pvw_create_sk(...)
  Node2 ->> Node2: pvw_create_sk(...)
  Node1 -->> Node2: PvwPubkeyCreated(index, pk)
  Node2 -->> Node1: PvwPubkeyCreated(index, pk)
  Node1 ->> Node1: generate_global_pubkey(pk[])
  Node2 ->> Node2: generate_global_pubkey(pk[])
  Node1 ->> Node1: calculate_pk_share_and_sk_sss(...)
  Node2 ->> Node2: calculate_pk_share_and_sk_sss(...)
  Node1 ->> Node1: calculate_esi_sss(...)
  Node2 ->> Node2: calculate_esi_sss(...)
  Node2 ->> DHT: PublishDocument(enc(sk_sss,esi_sss))
  Node2 -->> Node1: DocumentPublishedNotification
  Node1 ->> DHT: PublishDocument(enc(sk_sss,esi_sss))
  Node1 -->> Node2: DocumentPublishedNotification
  Node2 ->> DHT: FetchDocument
  DHT -->> Node2: FetchDocumentSucceeded
  Node1 ->> DHT: FetchDocument
  DHT -->> Node1: FetchDocumentSucceeded
  Node2 ->> Node2: extract_collected_sss <br/> gen_decryption_key
  Node1 ->> Node1: extract_collected_sss <br/> gen_decryption_key
  EVM -->> Node1: CiphertextOutputPublished
  Node1 ->> Node1: gen_decryption_share
  EVM -->> Node2: CiphertextOutputPublished
  Node2 ->> Node2: gen_decryption_share
  Node1 ->> Agg: DecryptionShareCreated
  Node2 ->> Agg: DecryptionShareCreated
  Agg -->> EVM: PlaintextAggregated
