sequenceDiagram
  participant E as EVM
  participant L as LibP2p
  participant CS as CiphernodeSelector
  participant S as Sortition
  participant K as ThresholdKeyshare
  participant K2 as PvwKeyAggregator

  E --) CS: E3Requested
  CS ->> S: am I selected?
  S -->> CS: yes
  CS --) K: create with CiphernodeSelected (via E3Router)
  K ->> K2: create with knowledge of m & n 
  rect rgb(230, 245, 255)
    K ->> K: StartPvwKeyGeneration
    Note over K, M2: PVW Key Generation
    K ->> K: pvw::gen_party()
    K ->> L: EncryptionPubkeyCreated
    K ->> K2: EncryptionPubkeyCreated
    L --) K2: EncryptionPubkeyCreated
    L --) K2: EncryptionPubkeyCreated
    K2 ->> K2: pvw::gen_public_key()
    K2 ->> K: GlobalEncryptionKeyAggregated
    K ->> L: GlobalEncryptionKeyAggregated
  end
  autonumber



