sequenceDiagram
  participant L as LibP2p
  participant K as ThresholdKeyshare
  participant M as Multithread(1)
  participant M2 as Multithread(2)

  rect rgb(230, 245, 255)
    K ->> K: StartThresholdShareGeneration
    Note over K, M2: Threshold Share Generation
    K ->> M: ComputeRequest(TrBFV::GenEsiSss)
    K ->> M2: ComputeRequest(TrBFV::GenPkShareAndSkSss)
    M ->> M: trbfv::gen_esi_sss()
    M2 ->> M2: trbfv::gen_pk_share_and_sk_sss()
    M --) K: ComputeRessponse(TrBFV::GenEsiSss)
    M2 --) K: ComputeRessponse(TrBFV::GenPkShareAndSkSss)
    K ->> K: pvw::encrypt_to_global_pubkey(sk_sss, esi_sss)
    K ->> L: ThresholdSharesCreated (shares)
  end
  autonumber



