sequenceDiagram
  participant E as EVM
  participant L as LibP2p
  participant K as ThresholdKeyshare
  participant M as Multithread(1)

  rect rgb(230, 245, 255)
    Note over K, M: Generate Decryption Share
    E --) K: CiphertextOutputPublished
    K ->> M: ComputeRequest(TrBFV::GenDecryptionShare)
    M ->> M: trbfv::calculate_decryption_share()
    M --) K: ComputeResponse(TrBFV::GenDecryptionShare)
    K ->> L: DecryptionShareCreated
  end
  autonumber



