sequenceDiagram
  participant L as LibP2p
  participant K as ThresholdKeyshare
  participant K3 as DecryptionKeyCollector
  participant M as Multithread(1)

  rect rgb(230, 245, 255)
    Note over K, M: Aggregating Decryption Key
    L --) K3: ThresholdSharesCreated (shares)
    L --) K3: ThresholdSharesCreated (shares)
    K3 ->> K: AllThresholdSharesCollected
    K ->> K: extract_collected_sss(pvw::decrypt())
    K ->> M: ComputeRequest(TrBFV::GenDecryptionKey)
    M ->> M: trbfv::calculate_decryption_key()
    M --) K: ComputeResponse(TrBFV::GenDecryptionKey)
    Note over K: Whilst we have had the <br/>PublicKeyshare for some time<br/> we only now send KeyshareCreated<br/> to indicate that we are ready to decrypt
    K ->> L: KeyshareCreated(pubkeyshare)
  end

  autonumber



