// SPDX-License-Identifier: LGPL-3.0-only
//
// This file is provided WITHOUT ANY WARRANTY;
// without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.

//! Cross-circuit commitment consistency links.
//!
//! Each [`CommitmentLink`] defines a relationship between two proof types
//! where a commitment value produced by one circuit must match a value
//! consumed or produced by another circuit. The
//! [`CommitmentConsistencyChecker`](super::commitment_consistency_checker::CommitmentConsistencyChecker)
//! evaluates these links as verified proofs arrive.

pub mod c0_to_c3;
pub mod c1_to_c5;
pub mod c4a_to_c6;
pub mod c4b_to_c6;
pub mod c6_to_c7;

use e3_events::ProofType;

/// A 32-byte BN254 field element extracted from public signals.
pub type FieldValue = [u8; 32];

/// How source and target proofs relate and where faults are attributed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LinkScope {
    /// Both proofs are generated by the same party (same Ethereum address).
    /// One source entry is compared to one target entry per address.
    SameParty,
    /// The source proof is per-party while the target is from a different
    /// party (e.g. per-node C1 vs aggregator C5). Each source's extracted
    /// value must appear in at least one target's public signals.
    /// Fault is attributed to the source if no target matches.
    CrossParty,
    /// Each source proof claims a value that must exist among the set of
    /// target proof outputs (from any party). Fault is attributed to the
    /// **source** when no target matches. Used when there are many source
    /// proofs (e.g. N-1 C3 proofs per sender) each referencing a different
    /// target (e.g. the recipient's C0 pk_commitment).
    SourceMustExistInTargets,
}

/// Defines a cross-circuit commitment consistency check.
///
/// Implementations extract commitment values from the public signals of a
/// *source* proof type and verify they are consistent with the public signals
/// of a *target* proof type.
pub trait CommitmentLink: Send + Sync {
    /// Human-readable name for logging.
    fn name(&self) -> &'static str;

    /// The proof type that *produces* the commitment value.
    fn source_proof_type(&self) -> ProofType;

    /// The proof type that *consumes* or must agree with the commitment value.
    fn target_proof_type(&self) -> ProofType;

    /// Relationship scope between source and target parties.
    fn scope(&self) -> LinkScope;

    /// Extract the commitment value(s) from the source proof's public signals.
    fn extract_source_values(&self, public_signals: &[u8]) -> Vec<FieldValue>;

    /// Return `true` when `source_values` are consistent with
    /// `target_public_signals`.
    fn check_consistency(&self, source_values: &[FieldValue], target_public_signals: &[u8])
        -> bool;
}

/// Returns the default set of commitment links to register.
///
/// C4→C6 links are disabled: the C4 Noir circuit and C6 Rust code compute
/// `compute_aggregated_shares_commitment` from incompatible representations
/// of the same aggregated polynomial (unreduced/uncentered/non-reversed vs
/// reduced/centered/reversed, plus different BIT parameters). See test
/// `c4_c6_commitment_mismatch_due_to_modular_reduction` in `c4a_to_c6.rs`.
/// Re-enable after aligning the commitment computation (circuit change needed).
pub fn default_links() -> Vec<Box<dyn CommitmentLink>> {
    vec![
        Box::new(c0_to_c3::C3aToC0PkCommitmentLink),
        Box::new(c0_to_c3::C3bToC0PkCommitmentLink),
        Box::new(c1_to_c5::C1ToC5PkCommitmentLink),
        Box::new(c6_to_c7::C6ToC7DCommitmentLink),
        // Box::new(c4a_to_c6::C4aToC6SkCommitmentLink),
        // Box::new(c4b_to_c6::C4bToC6ESmCommitmentLink),
    ]
}
