#!/usr/bin/env bash
set -euo pipefail

# Check if nargo command exists
if ! command -v nargo >/dev/null 2>&1; then
    echo "nargo command not found, skipping circuit checks"
    exit 0
fi

# Ensure we're in the right directory.
cd circuits

# Directories to check
DIRS=(
  "lib"
  "bin/config"
  "bin/recursive_aggregation/c2ab_fold"
  "bin/recursive_aggregation/c3_fold"
  "bin/recursive_aggregation/c3_fold_kernel"
  "bin/recursive_aggregation/c6_fold"
  "bin/recursive_aggregation/c6_fold_kernel"
  "bin/recursive_aggregation/c3ab_fold"
  "bin/recursive_aggregation/c4ab_fold"
  "bin/recursive_aggregation/node_fold"
  "bin/recursive_aggregation/nodes_fold"
  "bin/recursive_aggregation/nodes_fold_kernel"
  "bin/recursive_aggregation/dkg_aggregator"
  "bin/recursive_aggregation/decryption_aggregator"
  "bin/dkg"
  "bin/threshold"
)

for dir in "${DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        echo "Warning: Directory $dir does not exist, skipping..."
        continue
    fi
    
    echo "Checking $dir..."
    cd "$dir"
    
    # Checking circuit format.
    if ! (nargo fmt --check); then
        echo "Error: Circuit format check failed in $dir"
        exit 1
    fi
    
    # Check/validate the circuit libraries.
    if ! (nargo check); then
        echo "Error: Noir circuit check failed in $dir"
        exit 1
    fi
    
    # Remove all Prover.toml files (they're generated by nargo and in .gitignore)
    find . -name "Prover.toml" -type f -delete
    
    cd - > /dev/null
done

echo "Noir circuits checked successfully"
