#!/usr/bin/env bash
set -euo pipefail

# Check if nargo command exists
if ! command -v nargo >/dev/null 2>&1; then
    echo "nargo command not found, skipping circuit checks"
    exit 0
fi

# Ensure we're in the right directory.
cd circuits

# Directories to check
DIRS=("lib" "bin/aggregation" "bin/insecure" "bin/production")

for dir in "${DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        echo "Warning: Directory $dir does not exist, skipping..."
        continue
    fi
    
    echo "Checking $dir..."
    cd "$dir"
    
    # Find all package directories and create empty Prover.toml to prevent nargo from creating them
    created_files=()
    while IFS= read -r -d '' nargo_file; do
        pkg_dir=$(dirname "$nargo_file")
        prover_file="${pkg_dir}/Prover.toml"
        if [ ! -f "$prover_file" ]; then
            touch "$prover_file"
            created_files+=("$prover_file")
        fi
    done < <(find . -name "Nargo.toml" -type f -print0 2>/dev/null || true)
    
    # Checking circuit format.
    if ! (nargo fmt --check); then
        echo "Error: Circuit format check failed in $dir"
        exit 1
    fi
    
    # Check/validate the circuit libraries.
    if ! (nargo check); then
        echo "Error: Noir circuit check failed in $dir"
        exit 1
    fi
    
    # Remove all Prover.toml files (they're generated by nargo and in .gitignore)
    find . -name "Prover.toml" -type f -delete
    
    cd - > /dev/null
done

echo "Noir circuits checked successfully"
