// SPDX-License-Identifier: LGPL-3.0-only
pragma solidity >=0.8.26;

interface ICyphernodeState {
    /// @notice This event MUST be emitted when a cyphernode is added to the registry.
    event CyphernodeAdded(address indexed node);

    /// @notice This event MUST be emitted when a cyphernode is removed from the registry.
    event CyphernodeRemoved(address indexed node);

    function isCyphernodeEligible(
        address cyphernode
    ) external view returns (bool);

    /// @notice Verifies a committee and updates internal state triggered by the new committee becoming effective.
    /// @dev This function MUST revert if some of the nodes not eligible.
    /// @param e3Id ID of the E3 for which to select the committee.
    /// @param proof The public key generated by the selected committee.
    /// @param publicKey The public key generated by the selected committee.
    function verifyCommittee(
        uint256 e3Id,
        bytes calldata proof,
        bytes calldata publicKey
    ) external;
}
