#!/usr/bin/env bash
# scripts/generate_error_selectors.sh
# Generates Rust error selector mappings from Solidity contract ABIs

set -euo pipefail

if ! command -v jq &> /dev/null || ! command -v cast &> /dev/null; then
    echo "Error: Requires jq and cast (foundry)" >&2
    exit 1
fi

# Default ABI files
DEFAULT_ABIS=(
    "packages/enclave-contracts/artifacts/contracts/Enclave.sol/Enclave.json"
    "packages/enclave-contracts/artifacts/contracts/registry/CiphernodeRegistryOwnable.sol/CiphernodeRegistryOwnable.json"
    "packages/enclave-contracts/artifacts/contracts/registry/BondingRegistry.sol/BondingRegistry.json"
    "packages/enclave-contracts/artifacts/contracts/slashing/SlashingManager.sol/SlashingManager.json"
)

OUTPUT_FILE="src/error_selectors.rs"

# Use provided files or defaults
if [ $# -eq 0 ]; then
    ABI_FILES=("${DEFAULT_ABIS[@]}")
else
    ABI_FILES=("$@")
fi

# Extract errors from all ABI files, remove duplicates
ERRORS=$(for file in "${ABI_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        echo "Warning: File not found: $file" >&2
        continue
    fi
    jq -c '.[] | select(.type == "error")' "$file" 2>/dev/null || true
done | sort -u)

if [ -z "$ERRORS" ]; then
    echo "Error: No errors found in ABI files" >&2
    exit 1
fi

# Generate Rust file
cat > "$OUTPUT_FILE" << 'EOF'
// SPDX-License-Identifier: LGPL-3.0-only
//
// Auto-generated by scripts/generate_error_selectors.sh - DO NOT EDIT MANUALLY
// Run `./scripts/generate_error_selectors.sh` to regenerate after contract changes

/// Auto-generated error selector to name mapping
/// Format: (selector, error_name, [(param_name, param_type), ...])
pub static ERROR_SELECTORS: &[([u8; 4], &str, &[(&str, &str)])] = &[
EOF

first=true
while IFS= read -r error; do
    name=$(echo "$error" | jq -r '.name')
    inputs=$(echo "$error" | jq -r '.inputs // [] | map(.type) | join(",")')
    signature="${name}(${inputs})"
    
    selector=$(cast sig "$signature" 2>/dev/null)
    [ -z "$selector" ] && continue
    
    # Convert 0x7b054f9a to [0x7b, 0x05, 0x4f, 0x9a]
    selector="${selector#0x}"
    selector_array="[0x${selector:0:2}, 0x${selector:2:2}, 0x${selector:4:2}, 0x${selector:6:2}]"
    
    # Get parameters: &[("param1", "type1"), ...]
    params=$(echo "$error" | jq -r '.inputs // [] | map("(\"" + .name + "\", \"" + .type + "\")") | join(", ")')
    [ -z "$params" ] && params="&[]" || params="&[$params]"
    
    # Add comma separator
    [ "$first" = false ] && echo "," >> "$OUTPUT_FILE"
    first=false
    
    echo -n "    ($selector_array, \"$name\", $params)" >> "$OUTPUT_FILE"
done <<< "$ERRORS"

echo "" >> "$OUTPUT_FILE"
echo "];" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
