/* tslint:disable */
/* eslint-disable */
export const __wbg_encrypt_free: (a: number, b: number) => void;
export const __wbg_encryptionresult_free: (a: number, b: number) => void;
export const encryptionresult_encrypted_vote: (a: number) => [number, number];
export const encryptionresult_proof: (a: number) => [number, number];
export const encryptionresult_instances: (a: number) => any;
export const encrypt_new: () => number;
export const encrypt_encrypt_vote: (a: number, b: bigint, c: number, d: number) => [number, number, number];
export const __wbgt__crisp_web::test_encrypt_vote: (a: number) => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_start_worker: (a: number) => void;
export const __wbg_wasmbindgentestcontext_free: (a: number, b: number) => void;
export const wasmbindgentestcontext_new: () => number;
export const wasmbindgentestcontext_include_ignored: (a: number, b: number) => void;
export const wasmbindgentestcontext_filtered_count: (a: number, b: number) => void;
export const wasmbindgentestcontext_run: (a: number, b: number, c: number) => any;
export const __wbgtest_console_log: (a: any) => void;
export const __wbgtest_console_debug: (a: any) => void;
export const __wbgtest_console_info: (a: any) => void;
export const __wbgtest_console_warn: (a: any) => void;
export const __wbgtest_console_error: (a: any) => void;
export const __wbgtest_cov_dump: () => [number, number];
export const __externref_table_alloc: () => number;
export const __wbindgen_export_1: WebAssembly.Table;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const closure484_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures__invoke0_mut__hcff76a7c86b47304: (a: number, b: number) => void;
export const closure660_externref_shim: (a: number, b: number, c: any, d: number, e: any) => void;
export const closure664_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
